# Generated by Django 5.2.8 on 2026-07-27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_remove_userprofile_ai_lab_activated_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="groq_api_key",
        ),
    ]
