"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

try:
    import dotenv
    # backend/.env
    dotenv.load_dotenv(BASE_DIR / ".env")
except ImportError:
    print("dotenv is not installed. Please install it using 'pip install python-dotenv'")
    exit(1)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', "django-insecure-=n$w94*lbh^8$sk09d3@mq6mxymnf+_p0d4_=(nv2u!bsm7j2&")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1,0.0.0.0').split(',')

# CSRF 信任域名配置 - 必须放在文件前面确保生效
# 这是解决 Nginx 代理 + HTTPS 时 CSRF 验证失败的关键配置
CSRF_TRUSTED_ORIGINS = [
    # 新域名 - lzqqq.org
    'https://lzqqq.org',
    'https://www.lzqqq.org',
    'http://lzqqq.org',
    'http://www.lzqqq.org',
    # 旧域名 - lzqqqkitchen.org (迁移期间保留)
    'https://lzqqqkitchen.org',
    'https://www.lzqqqkitchen.org',
    'http://lzqqqkitchen.org',
    'http://www.lzqqqkitchen.org',
    # 本地开发
    'http://localhost:8000',
    'http://127.0.0.1:8000',
]

# 确保正确处理代理后的 HTTPS
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')



# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "rest_framework",
    "corsheaders",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "api",
    "cards",
    "readings",
    "oracle",
    "questions",  # QuestionGen 刷题模块
    "accounts",
    "receipts",
]

SITE_ID = 1

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# CORS 配置
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True  # 开发环境
else:
    # 生产环境：只允许特定域名
    CORS_ALLOWED_ORIGINS = os.environ.get(
        'CORS_ALLOWED_ORIGINS', 
        'https://yourdomain.com'
    ).split(',')


ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"
ASGI_APPLICATION = "config.asgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": os.environ.get('DB_ENGINE', "django.db.backends.sqlite3"),
        "NAME": os.environ.get('DB_NAME', str(BASE_DIR / "db.sqlite3")),
        "USER": os.environ.get('DB_USER', ''),
        "PASSWORD": os.environ.get('DB_PASSWORD', ''),
        "HOST": os.environ.get('DB_HOST', ''),
        "PORT": os.environ.get('DB_PORT', ''),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

DEFAULT_CURRENCY = os.environ.get("DEFAULT_CURRENCY", "GBP")

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=90),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": False,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# 厨师登录凭证（从环境变量读取，默认值仅用于开发）
CHEF_USERNAME = os.environ.get('CHEF_USERNAME', 'chef')
CHEF_PASSWORD = os.environ.get('CHEF_PASSWORD', 'kitchen123')

# DeepSeek API 配置
DEEPSEEK_API_KEY = os.environ.get('DEEPSEEK_API_KEY', '')
DEEPSEEK_BASE_URL = os.environ.get('DEEPSEEK_BASE_URL', 'https://api.deepseek.com')

# 硅基流动 API 配置 (用于 DeepSeek-OCR)
SILICONFLOW_API_KEY = os.environ.get('SILICONFLOW_API_KEY', '')
SILICONFLOW_BASE_URL = os.environ.get('SILICONFLOW_BASE_URL', 'https://api.siliconflow.cn/v1')

# OpenRouter API 配置 (用于 StepFun 等第三方模型)
OPENROUTER_API_KEY = os.environ.get('OPENROUTER_API_KEY', '')

# Serper API 配置 (用于网页搜索工具)
SERPER_API_KEY = os.environ.get('SERPER_API_KEY', '')

# Google CSE 配置 (用于网页搜索工具，主搜索引擎)
GOOGLE_CSE_API_KEY = os.environ.get('GOOGLE_CSE_API_KEY', '')
GOOGLE_CSE_CX = os.environ.get('GOOGLE_CSE_CX', '')

# Fernet encryption key for sensitive fields (API keys stored in DB)
# Auto-generated on first run and persisted to .env
FIELD_ENCRYPTION_KEY = os.environ.get('FIELD_ENCRYPTION_KEY', '')
if not FIELD_ENCRYPTION_KEY:
    from cryptography.fernet import Fernet as _Fernet
    FIELD_ENCRYPTION_KEY = _Fernet.generate_key().decode()
    # Persist to .env so subsequent restarts use the same key
    _env_path = BASE_DIR / ".env"
    with open(_env_path, "a") as _f:
        _f.write(f"\nFIELD_ENCRYPTION_KEY={FIELD_ENCRYPTION_KEY}\n")
    del _Fernet, _env_path, _f

# Groq API 配置（用于厨房聊天组件的 Whisper 语音转录）
GROQ_API_KEY = os.environ.get('GROQ_API_KEY', '')

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APPS": [{
            "client_id": os.environ.get("GOOGLE_OAUTH_CLIENT_ID", ""),
            "secret": os.environ.get("GOOGLE_OAUTH_SECRET", ""),
        }],
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {"access_type": "online"},
    }
}

GOOGLE_OAUTH_CLIENT_ID = os.environ.get("GOOGLE_OAUTH_CLIENT_ID", "")

# HTTPS 安全配置 (生产环境)
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = False  # Nginx 已处理 HTTPS 重定向
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
